### ISSUE TITLE
Json files of the MVSD-QA dataset

### ISSUE THREAD

**Issue by Hou9612** [DAMO-NLP-SG/VideoLLaMA2#100]
Congratulations on this wonderful work!

The readme file suggests preparing test_q.json and test_a.json for evaluation on the MVSD-QA dataset, but on the official website of the MVSD-QA dataset, I can only download test_qa.json. How can I make test_q.json and test_a.json files based on the test_qa.json file, or where can I get test_q.json and test_a.json files?

**Comment by clownrat6** [comment]
VideoChatGPT doesn't provide MSVD official questions and answers, but provide the generation method of questions and answers. Therefore, different papers may adopt different test set of MSVD dataset. Following previous works, the MSVD-QA dataset adopted by us is generated by Video-LLaVA. However, we do not suggest to evaluate VideoLLM on MSVD-QA because it seems to be evaluated unconsistently across different papers.

**Comment by Hou9612** [comment]
> VideoChatGPT doesn't provide MSVD official questions and answers, but provide the generation method of questions and answers. Therefore, different papers may adopt different test set of MSVD dataset. Following previous works, the MSVD-QA dataset adopted by us is generated by Video-LLaVA. However, we do not suggest to evaluate VideoLLM on MSVD-QA because it seems to be evaluated unconsistently across different papers.

Thanks very much for your reply!
