### ISSUE TITLE
[BUG] The following error will be reported when training custom data

### ISSUE THREAD

**Issue by xiexiaoshinick** [DAMO-NLP-SG/VideoLLaMA2#19]
![image](https://github.com/DAMO-NLP-SG/VideoLLaMA2/assets/26023731/dbae98a7-5324-455a-be1f-f31484609e27)

**Comment by lixin4ever** [comment]
Could you please provide more details (like code snippet and training config) so that we can reproduce your error?

**Comment by xiexiaoshinick** [comment]
Thank you for your reply. I organized the dataset according to the requirements of readme, and the data is as follows:
![image](https://github.com/DAMO-NLP-SG/VideoLLaMA2/assets/26023731/b2c1b974-10e4-4a45-a29a-5789bb13bd0b)
My training config
[finetune.txt](https://github.com/user-attachments/files/15942537/finetune.txt)
no other changes to the code

**Comment by gyxxyg** [comment]
I have encountered the same issue before. Maybe only use one '<video>\n' in the conversation can help, as the video is only encoded once.

**Comment by lixin4ever** [comment]
@xiexiaoshinick Sorry for the late reply.
@gyxxyg is correct, we use only one <video> for each conversation and this special token is placed in the first turn of the conversation.

**Comment by xiexiaoshinick** [comment]
@lixin4ever @gyxxyg Thank you for your reply, solve my problem perfectly, and look forward to adding VideoLlama2 version of the voice modality later

**Comment by sjghh** [comment]
Hello, I encountered this error while inputting a video for fine-tuning. I am sure that the path is correct. Is it because the video must be in MP4 format, or can AVI be used? Thank you for your reply. 


 [04:17:43] /github/workspace/src/video/video_reader.cc:83: ERROR opening: /data/video-llama2/VideoLLaMA2-main/datasets/custom_sft/videos/samplenew_00018773.mp4, Invalid data found when processing input
Traceback (most recent call last):
  File "/data/video-llama2/VideoLLaMA2-main/videollama2/train.py", line 315, in __getitem__
    video = process_video(video_file, video_processor, aspect_ratio=self.data_args.image_aspect_ratio, num_frames=num_frames)
  File "/data/video-llama2/VideoLLaMA2-main/videollama2/mm_utils.py", line 155, in process_video
    vreader = VideoReader(video_path, ctx=cpu(0), num_threads=1)
  File "/opt/conda/envs/Videollama2/lib/python3.9/site-packages/decord/video_reader.py", line 57, in __init__
    raise RuntimeError("Error reading " + uri + "...")
RuntimeError: Error reading /data/video-llama2/VideoLLaMA2-main/datasets/custom_sft/videos/samplenew_00018773.mp4...
Encounted error when reading video /data/video-llama2/VideoLLaMA2-main/datasets/custom_sft/videos/samplenew_00018773.mp4, use 58067-th example instead!!!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x13b77940] moov atom not found
